set encoding=utf-8

augroup vimrc
      autocmd!
augroup END

if has('kaoriya')
    let g:no_vimrc_example=0
    let g:vimrc_local_finish=1
    let g:gvimrc_local_finish=1
 
    "$VIM/plugins/kaoriya/autodate.vim
    let plugin_autodate_disable  = 1
    "$VIM/plugins/kaoriya/cmdex.vim
    let plugin_cmdex_disable     = 1
    "$VIM/plugins/kaoriya/dicwin.vim
    let plugin_dicwin_disable    = 1
    "$VIMRUNTIME/plugin/format.vim
    let plugin_format_disable    = 1
    "$VIM/plugins/kaoriya/hz_ja.vim
    let plugin_hz_ja_disable     = 1
    "$VIM/plugins/kaoriya/scrnmode.vim
    let plugin_scrnmode_disable  = 1
    "$VIM/plugins/kaoriya/verifyenc.vim
    let plugin_verifyenc_disable = 1
endif
if !has('nvim')
    source $VIMRUNTIME/defaults.vim
endif
" vimplugin settings start
" ============================================================================

if filereadable(expand('~/.vim/autoload/plug.vim'))
            \|| filereadable(expand('~/AppData/Local/nvim/autoload/plug.vim'))
            \|| filereadable(expand('~/vimfiles/autoload/plug.vim'))
    if has('nvim') && has('win32') " Neovim on Windows
        let g:local = '~/AppData/Local/nvim/plugged'
    elseif has('unix') "vim on Linux
        let g:local = '~/.vim/plugged'
    else "gVim on Windows
        let g:local = '~/vimfiles/plugged'
    endif
    call plug#begin(local)
    if has('nvim')
    " Neovimのみのプラグイン
    else
    " ノーマルvimのみのプラグイン
        Plug 'roxma/nvim-yarp'
        Plug 'roxma/vim-hug-neovim-rpc'
    endif
    "Plug 'hougo/neocomplcache.vim'
    Plug 'vim-jp/vimdoc-ja'
    Plug 'tpope/vim-sensible'
    Plug 'prabirshrestha/async.vim'
    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/asyncomplete-lsp.vim'
    Plug 'prabirshrestha/vim-lsp'
    Plug 'mattn/vim-lsp-settings'
    Plug 'mattn/vim-lsp-icons'
    Plug 'tpope/vim-surround'
    " FuzzyFinder
    Plug 'ctrlpvim/ctrlp.vim'

    " マルチカーソル
    Plug 'mg979/vim-visual-multi'

    " 分割リサイズ https://github.com/simeji/winresizer#customize-options
    Plug 'simeji/winresizer'

    "vimとGitの連携
    Plug 'airblade/vim-gitgutter'
    Plug 'tpope/vim-fugitive'

    " Linter系
    "Plug 'neomake/neomake'
    "Plug 'scrooloose/syntastic'
    
    " ColorScheme
    Plug 'nanotech/jellybeans.vim'
    Plug 'tomasr/molokai'
    Plug 'ayu-theme/ayu-vim'
    Plug 'Rigellute/rigel'
    "Plug 'NLKNguyen/papercolor-theme'
    " status bar
    Plug 'itchyny/lightline.vim'
    call plug#end()

    "vim-visual-multi
    nnoremap <silent> <M-j> <C-n>

    "status line plugin
    "colorscheme ayu_dark wombat PaperColor one
    set noshowmode "ノーマルのモード表示をオフにする
    let g:lightline = {
                \ 'colorscheme': 'rigel',
                \ 'mode_map': {'c': 'NORMAL'},
                \ 'active': {
                \   'left': [   [ 'mode', 'paste' ],
                \               [ 'gitbranch', 'gitgutter', 'readonly', 'filename', 'modidied'],
                \           ],
                \   'right' : [ [ 'lineinfo', 'syntastic' ], 
                \               [ 'percent' ],
                \               [ 'charcode', 'fileformat', 'fileencoding', 'filetype' ],
                \             ]
                \ },
                \ 'component_function': {
                \   'gitbranch':    'MyFugitive',
                \   'gitgutter':    'MyGitGutter',
                \ },
                \ 'separator': {'left': "\ue0bc", 'right': "\ue0ba"},
                \ 'subseparator': {'left': "\ue0bd", 'right': "\ue0bd"}
                \ }
    " https://www.nerdfonts.com/cheat-sheet
    let g:lightline#ale#indicator_checking = " \uf110 "
    let g:lightline#ale#indicator_warnings = "\uf071 "
    let g:lightline#ale#indicator_errors = "\uf05e "
    let g:lightline#ale#indicator_ok = "\uf00c "
    function! MyFugitive()
        try
            "if exists(FugitiveHead())
                let _ = FugitiveHead()
                return strlen(_) ? "\ue0a0 "._ : ''
            "endif
        catch
        endtry
        return ''
    endfunction
    let g:gitgutter_sign_added = '✚'
    let g:gitgutter_sign_modified = '➜'
    let g:gitgutter_sign_removed = '✘'
    function! MyGitGutter()
        if ! exists('*GitGutterGetHunkSummary')
                    \ || ! get(g:, 'gitgutter_enabled', 0)
                    \ || winwidth('.') <= 90
            return ''
        endif
        let symbols = [
                    \ g:gitgutter_sign_added . '',
                    \ g:gitgutter_sign_modified . '',
                    \ g:gitgutter_sign_removed . ''
                    \ ]
        let hunks = GitGutterGetHunkSummary()
        let ret = []
        for i in [0, 1, 2]
            if hunks[i] > 0
                call add(ret, symbols[i]. " ". hunks[i])
            endif
        endfor
        return join(ret, ' ')
    endfunction

    "syntasticの設定
    function! SyntasticSettings() abort
        let g:syntastic_check_on_open = 1
        "let g:syntastic_python_checkers = ['flake8', 'pep257', 'mypy']
        let g:syntastic_python_checkers = ['flake8', 'pep257', 'mypy']
        let g:syntastic_python_flake8_args = '--max-line-length=120'
    endfunction
    augroup syntastic_settings
        autocmd!
        autocmd User lsp_setup call SyntasticSettings()
    augroup END

    ""neomakeの設定
    "let g:neomake_python_enabled_makers = ['python', 'flake8', 'mypy']

    "augroup neomake
    "autocmd!
    "autocmd FileType python setlocal omnifunc=jedi#completions
    "augroup END
    "if !exists('g:neocomplete#force_omni_input_patterns')
    "    let g:neocomplete#force_omni_input_patterns = {}
    "endif
    "let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

    " lspの設定
    let g:asyncomplete_popup_delay = 200
    let g:lsp_text_edit_enabled = 1
    let g:lsp_diagnostics_enabled = 1 "リアルタイムのエラー表示を有効にする
    let g:lsp_diagnostics_echo_cursor = 1 "エラー行にカーソルをあわせたときにエラーの理由をする
    let g:lsp_diagnostics_float_cursor = 1 "LSPのメッセージをポップアップウィンドウで表示する
    let g:lsp_signs_enabled = 1 "エラーの表示をファイルに直接する
    let g:lsp_log_verbose = 1
    let g:lsp_log_file = expand('~/vim-lsp.log')
    " asyncomplete.vim log
    "let g:asyncomplete_log_file = expand('~/asyncomplete.log')

    " pylsの設定。LinterのON/OFFなどが可能
    let s:pyls_config = {'pyls': {'plugins': {
                \   'pycodestyle': {'enabled': v:false},
                \   'pydocstyle': {'enabled': v:false},
                \   'pylint': {'enabled': v:false},
                \   'flake8': {'enabled': v:false},
                \   'jedi_definition': {
                \     'follow_imports': v:true,
                \     'follow_builtin_imports': v:true,
                \   },
                \ }}}
    " pylsの起動定義
    if executable('pyls')
        augroup LspPython
            autocmd!
            autocmd User lsp_setup call lsp#register_server({
                        \ 'name': 'pyls',
                        \ 'cmd': { server_info -> ['pyls'] },
                        \ 'whitelist': ['python'],
                        \ 'workspace_config': s:pyls_config
                        \})
        augroup END
    endif
    

    " omnisharpの設定 + Lspのキーバインド
    function! s:on_lsp_buffer_enabled() abort
        setlocal omnifunc=lsp#complete
        setlocal signcolumn=yes
        nmap <buffer> gd <plug>(lsp-definition)
        nmap <buffer> <f2> <plug>(lsp-rename)
        nnoremap <silent> cre :LspRename<CR> "リファクタリング・リネーム
        nnoremap <silent> <C-]> :LspDefinition<CR> "定義ジャンプ
        nnoremap <silent> <C-.> :<C-u>LspCodeAction<CR>
        nnoremap <silent> gh :<C-u>LspHover<CR> "ghに割り当てると選択モードが使えなくなる
        nnoremap <Leader>n :<C-u>LspReferences<CR>
        nnoremap <Leader>f :<C-u>LspDocumentDiagnostics<CR>
        nnoremap <Leader>s :<C-u>LspDocumentFormat<CR>
    endfunction
    augroup lsp_install
        au!
        autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
    augroup END

    " winresizer の設定
    let g:winresizer_vert_resize = 6
    let g:winresizer_horiz_resize = 2
    let g:winresizer_start_key = '<C-e>'

    " CtrlP の設定
    nnoremap ,, :CtrlPMRU<CR>
    
 
endif
" vimplugin setting END ======================================================

" コマンドライン補完
if !has('nvim')
set wildmenu
set wildmode=list:full
endif

" vim の矩形選択で文字が無くても右へ進める
set virtualedit=block

" 補完表示時のEnterで改行をしない
inoremap <expr><CR>  pumvisible() ? "<C-y>" : "<CR>"

" menuone補完が一個しかなくても常に補完を出すのと補完候補を挿入しない。
set completeopt=menuone,noinsert

"Terminal設定
if has('nvim')
    " <C-w>でvimと同じ動きにする
    tnoremap <C-w> <C-\><C-n><C-w> " 
     " ターミナルに切り替えたとき自動的にインサートモードにする
    "augroup WinEnterInsertMode
        "autocmd!
        "autocmd WinEnter * if &buftype ==# 'terminal' | startinsert | endif
    "augroup END
elseif !has('nvim')
    " ターミナルに移ったときにインサートモードを抜けてノーマルモードにする
    " \<C-\>\<C-n>のように\でスケープすると、キー入力として呼び出せる
    augroup WinEnterInsertMode_!nvim
        autocmd!
        autocmd WinEnter * if &buftype ==# 'terminal' | call timer_start(0, { -> feedkeys("\<C-\>\<C-n>") }) | endif
    augroup END
endif
" 既にターミナルを開いているときの処理
function! TermOpen()
    if has('nvim')
        execute "sp|term"
        "startinsert
    else
        if empty(term_list())
            execute "terminal"
        else
            call win_gotoid(win_findbuf(term_list()[0])[0])
        endif
    endif
endfunction

noremap <silent> <Space>@ :call TermOpen()<CR>

" 水平分割時に下に追加されるようになる
set splitbelow

if version >= 801
    " ターミナルの高さx幅
    set termwinsize=9x0
endif

" シェルのパス
"if has('win32') && has('nvim')
"   " set shell=pwsh.exe
"   " set shellcmdflag=-NoProfile\ -NoLogo\ -NonInteractive\ -Command
"endif

" バッファを閉じるときに保存しなくても良い
set hidden

"コード自動判定
set fileformats=unix,dos,mac

"ファイルエンコーディング自動判定
set fileencodings=utf-8,cp932,sjis,iso-2022-jp,euc-jp


" タブの幅設定
"set noexpandtab
set expandtab
set tabstop=4
set shiftwidth=0

" Python設定
autocmd FileType python setlocal tabstop=4

" python3とRuby
if has('win32') && ('nvim')
    let g:python3_host_prog = '~\Anaconda3\python.EXE'
    let g:python_host_prog = '~\Anaconda3\envs\py27\python.EXE'
    let g:ruby_host_prog = '~\scoop\apps\ruby\current\gems\bin\neovim-ruby-host.bat'
elseif has('unix') && ('nvim')
endif

" 256色
set t_Co=256~

" True Color(24bit Color) サポート
"set termguicolors
if has('nvim')
    set termguicolors
endif

if has('nvim') 
    " 補完ウィンドウ等の透明度0~100
    set pumblend=20
    " floating window の透明度 0~100
    set winblend=18
endif



" clipboardを有効にする
if has('nvim') || !has('win32')
set clipboard&
set clipboard^=unnamedplus
endif

" マウスを有効にする
"set mouse=a

" マウススクロールを有効にする
"set ttymouse=xterm2

" ノーマルモード中にEnterで下に行を追加
"noremap <CR> o<Esc>

"x キー削除でデフォルトレジスタに入れない
nnoremap x "_x
vnoremap x "_x

"折り返した行内を移動
noremap j gj
noremap k gk

"インサートモードで bash 風キーマップ
"inoremap <C-a> <C-o>^
"inoremap <C-e> <C-o>$<Right>
"inoremap <C-b> <Left>
"inoremap <C-f> <Right>
"inoremap <C-n> <Down>
"inoremap <C-p> <Up>
"inoremap <C-h> <BS>
"inoremap <C-d> <Del>
"inoremap <C-k> <C-o>D<Right>
"inoremap <C-u> <C-o>d^
"inoremap <C-w> <C-o>db

" 改行無しのカーソルから文末までコピー
nnoremap Y y$

"バッファの切り替えを<C-j> <C-k>で行う
nnoremap <silent> <C-h> :bprev<CR>
nnoremap <silent> <C-l> :bnext<CR>

" 選択範囲のインデントを連続して変更
vnoremap < <gv
vnoremap > >gv

" スクロール時に表示を指定行確保
set scrolloff=40

" ファイル名表示
"set statusline=%F 

" 行、列番号
"set statusline=%f%m%=%3l,%3c

" ステータスラインカスタマイズ
set statusline=
set statusline+=%F%m%r%h%w\ %<[ENC=%{&fenc!=''?&fenc:&enc}]\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%04.3b]\ [HEX=\%02.2B]\ [LEN=%L]%=(%02l,%02v)\ %p%%\ 
"色の付け方"%#Visual#

"ルーラーの表示
set ruler

" 変更のチェック表示
"set statusline+=%m

" ステータスラインの表示 0:表示しない 1:2つ以上ウィンドウがあるときのみ 2:常に表示
set laststatus=2

" ステータスラインの縦幅
set cmdheight=1

" 内容が変更されたら自動リロード
set autoread

" 行番号表示
set number

" ファイルを上書きする前にバックアップを作ることを無効化
set nowritebackup

" 検索するときに大文字小文字を区別しない
set ignorecase

" 検索時に大文字を含んでいたら大/小を区別
set smartcase

" 行末のスペースを可視化
set nolist
set listchars=tab:^\ ,trail:~,eol:↲

" 不可視文字（tab:tab,trail:行末スペース,nbsp:ノーブレークスペース,eol:改行）
"set list
"set listchars=tab:»-,trail:-,nbsp:%,eol:↲

" 対応する括弧を強調表示
set showmatch

" タイトルを表示
set title

" シンタックスハイライト
syntax on

" 現在の行を強調表示
set cursorline

augroup ColorSchemeSetting
    colorscheme rigel
    " ayu color
    "colorscheme ayu
    "ayucolor="light"  " for light version of theme
    "let ayucolor="mirage" " for mirage version of theme
    "let ayucolor="dark"   " for dark version of theme
    
    "colorscheme PaperColor " カラースキーマ

    " カラースキーマ
    "colorscheme molokai
    " ダーク系のカラースキームを使う
    set background=dark

    " コメント色
    highlight Comment ctermfg=DarkGreen
    if has('nvim')
        " 256Color のときのカレント行の色設定
        "autocmd ColorScheme * highlight CursorLine cterm=underline ctermfg=NONE "ctermbg=NONE
        " 24bitColorのときのカレント行の色設定
        "autocmd ColorScheme * highlight CursorLine gui=underline guifg=NONE guibg=NONE ctermbg=NONE
        highlight CursorLine gui=underline guifg=NONE guibg=NONE ctermbg=NONE
        " 背景色設定
        highlight Normal guibg=NONE
        highlight LineNr guibg=NONE
        highlight VertSplit guibg=NONE
        highlight Special guibg=NONE
        highlight Identifier guibg=NONE
        highlight NonText guibg=NONE
    else
        if &termguicolors
            " 24bitColorのときのカレント行の色設定
            autocmd ColorScheme * highlight CursorLine cterm=underline guifg=NONE guibg=NONE
            " 24bitColorのときの背景色設定
            highlight Normal guibg=Gray3
            highlight LineNr guibg=Gray3
            highlight VertSplit guibg=Gray3
            highlight Special guibg=Gray3
            highlight Identifier guibg=Gray3
            highlight NonText guibg=Gray3
        else
            " 256Color のときのカレント行の色設定
            highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE
            "autocmd ColorScheme * highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE
            " 256Color のときの背景色の設定
            "highlight Normal guibg=NONE
            "highlight LineNr guibg=NONE
            "highlight VertSplit guibg=NONE
            "highlight Special guibg=NONE
            "highlight Identifier guibg=NONE
            if has('unix') " Windows上で背景を透過できない不具合?対策
                highlight Normal ctermbg=NONE
                highlight LineNr ctermbg=NONE
                highlight VertSplit ctermbg=NONE
                highlight Special ctermbg=NONE
                highlight Identifier ctermbg=NONE
                highlight EndOfBuffer ctermbg=NONE
                highlight Folded ctermbg=NONE
                highlight Conceal ctermbg=NONE
                highlight NonText ctermbg=NONE
            endif
        endif
    endif

    " Errorの色を変更
    highlight Error ctermfg=15 ctermbg=9 guifg=#F6F1DF guibg=#882929
    " Todoの色設定
    highlight Todo ctermfg=0 guifg=#F78A81

augroup END

" termguicolors
if has("terminal") && has("nvim")
if version >= 800
    let g:terminal_ansi_colors = [
                \ '#073642', " black                30m
                \ '#E06C75', " Red                  31m
                \ '#98C379', " green                32m
                \ '#E5C07B', " yellow               33m
                \ '#61AFEF', " blue                 34m
                \ '#C678DD', " magenta              35m
                \ '#56B6C2', " cyan                 36m
                \ '#DCDFE4', " white                37m
                \ '#5A6374', " black (bright)
                \ '#E06C75', " red (bright)
                \ '#98C379', " green (bright)
                \ '#E5C07B', " yellow (bright)
                \ '#61AFEF', " blue (bright)
                \ '#C678DD', " magenta (bright)
                \ '#56B6C2', " cyan (bright)
                \ '#DCDFE4', " white (bright)
                \ ]
endif " version >= 800
endif " has("terminal")

" 現在の行を強調表示（縦）
"set cursorcolumn

" 行末の1文字先までカーソルを移動できるように
"set virtualedit=onemore

" 検索時に最後まで行ったら最初に戻る
set wrapscan

" 検索語をハイライト表示
set hlsearch

" 折り返さない
set wrap

" オートインデント
set autoindent

" 現在のファイルパス確認
:command! Mfile echo expand("%:p")

"ターミナルの指定
if has('win32') "Windows
    if executable('pwsh')
        set shell=pwsh
    elseif executable('powershell')
        set shell=powershell
    endif
endif

" Neovide
if (exists("g:neovide"))
    colorscheme ayu
    " コメント色
    highlight Comment ctermfg=DarkGreen
    " Errorの色を変更
    highlight Error ctermfg=15 ctermbg=9 guifg=#F6F1DF guibg=#882929
    " Todoの色設定
    highlight Todo ctermfg=0 guifg=#F78A81
    let g:neovide_remember_window_size = v:true
    let g:neovide_cursor_vfx_mode = "railgun"
    let g:neovide_cursor_vfx_mode = "ripple"
    set guifont=CaskaydiaCove\ Nerd\ Font\ Mono:h12
    let g:neovide_transparency=0.95
    function! ToggleFullscreen()
        if g:neovide_fullscreen == v:true
            let g:neovide_fullscreen=v:false
        else
            let g:neovide_fullscreen=v:true
        endif
    endfunctio
    nnoremap <silent><F11> :call ToggleFullscreen()<CR>
endif

