#bashのエイリアス専用ファイル

alias python=python3
#alias python=python2
#echo ".bash_aliasesが読み込まれました"

alias mv="mv -i"
alias explorer="nautilus"


# Docker: 最後のコンテナのログ末尾20行を表示
alias dlogs='docker logs $(docker ps -lq) 2>&1 | tail -20'
